# Generated by Django 2.2.6 on 2019-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PgDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgName', models.CharField(max_length=200)),
                ('pgCity', models.CharField(max_length=200)),
                ('pgLocation', models.CharField(max_length=200)),
                ('pgAddress', models.TextField(max_length=500)),
                ('pgImage1', models.ImageField(upload_to='')),
                ('pgImage2', models.ImageField(upload_to='')),
                ('pgImage3', models.ImageField(upload_to='')),
                ('pgRating', models.IntegerField(max_length=2)),
                ('pgDescription', models.TextField(max_length=5000)),
                ('pgRules', models.TextField(max_length=1000)),
                ('pgFood', models.TextField(max_length=500)),
                ('pgRoom', models.IntegerField(max_length=3)),
                ('pgCharge', models.IntegerField(max_length=5)),
            ],
        ),
    ]
