# Generated by Django 2.2.6 on 2019-10-29 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pg_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pgdetail',
            name='pgBathroom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pgdetail',
            name='pgFor',
            field=models.CharField(default='Boys and Girls', max_length=20),
        ),
        migrations.AddField(
            model_name='pgdetail',
            name='pgLaundry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pgdetail',
            name='pgMail',
            field=models.EmailField(default=1234, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pgdetail',
            name='pgPhone',
            field=models.CharField(default='122', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pgdetail',
            name='pgWiFi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pgdetail',
            name='pgCharge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pgdetail',
            name='pgImage1',
            field=models.ImageField(upload_to='pg_pics'),
        ),
        migrations.AlterField(
            model_name='pgdetail',
            name='pgImage2',
            field=models.ImageField(upload_to='pg_pics'),
        ),
        migrations.AlterField(
            model_name='pgdetail',
            name='pgImage3',
            field=models.ImageField(upload_to='pg_pics'),
        ),
        migrations.AlterField(
            model_name='pgdetail',
            name='pgRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pgdetail',
            name='pgRoom',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_detail.PgDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pgdetail',
            name='user',
            field=models.OneToOneField(default='jnkhnj', on_delete=django.db.models.deletion.CASCADE, to='pg_detail.PgOwner'),
            preserve_default=False,
        ),
    ]
