# Generated by Django 2.2.6 on 2019-10-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg_detail', '0002_auto_20191029_0814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
