# Generated by Django 2.2.6 on 2019-10-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pg_detail', '0005_pgowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pg_detail.PgOwner'),
        ),
    ]
