# Generated by Django 2.2.6 on 2019-11-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_detail', '0011_auto_20191029_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgdetail',
            name='pgRating',
            field=models.FloatField(),
        ),
    ]
